### ISSUE TITLE
(question) banning

### ISSUE THREAD

**Issue by velamyGH** [XeathJP/A-client-for-Discord-for-3DS#1]
this seems to be code from the original 3discord, is there a risk of ban on accounts just like that version? or has code been edited to ensure that doesnt happen

**Comment by XeathJP** [comment]
There is almost no chance of being banned if it is a direct message. If you chat on a server, the possibility is normal and at your own risk!

**Comment by velamyGH** [comment]
alrighty, doubt ill be using this much but when i do i will keep this in mind whenever it is needed :)
